### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lleddoncchung** [LeDonChung/JavaCode#3]
Hello, LeDonChung

**Comment by lleddoncchung** [comment]
public Connection getConnection() {
		try {
			// load driver
			Class.forName(resourceBundle.getString("driverName"));
			String url = resourceBundle.getString("url");
			String userName = resourceBundle.getString("userName");
			String password = resourceBundle.getString("password");
			return DriverManager.getConnection(url, userName, password);

		} catch (ClassNotFoundException e) {
			return null;
		} catch (SQLException e) {
			return null;
		}
	}

**Comment by LeDonChung** [comment]
tks bro
